### PR TITLE
Add --compressed flag to cURL commands

### LINKED ISSUE #10: Fails to obtain GHC version
```
% asdf install haskell 8.6.3
ghc version:
Installing Haskell 8.6.3 (ghc-)
STACK_ROOT=/Users/patrickoscity/.asdf/installs/haskell/8.6.3/stack
option --compiler: Failed to parse compiler: ghc-

Usage: stack [--help] [--version] [--numeric-version] [--hpack-numeric-version]
             [--docker*] [--nix*] ([--verbosity VERBOSITY] | [-v|--verbose] |
             [--silent]) [--[no-]time-in-log] [--stack-root STACK-ROOT]
             [--work-dir WORK-DIR] [--[no-]system-ghc] [--[no-]install-ghc]
             [--arch ARCH] [--ghc-variant VARIANT] [--ghc-build BUILD]
             [-j|--jobs JOBS] [--extra-include-dirs DIR] [--extra-lib-dirs DIR]
             [--with-gcc PATH-TO-GCC] [--with-hpack HPACK]
             [--[no-]skip-ghc-check] [--[no-]skip-msys] [--local-bin-path DIR]
             [--[no-]modify-code-page] [--[no-]allow-different-user]
             [--[no-]dump-logs] [--resolver RESOLVER] [--compiler COMPILER]
             [--[no-]terminal] [--color WHEN] [--terminal-width INT]
             [--stack-yaml STACK-YAML] COMMAND|FILE
```

The HTTP response will be gzipped, I assume that was not the case before. I could get it to work for now by adding the `--compressed` flag to the `curl` command.

### PR DESCRIPTION
**Pull request by brianvanburken**
This fixes #10.

### CODE REVIEW

**Comment by nelsonmestevao** [comment]
Please, check out what is wrong with travis-ci because this really fixes #10! :pray: 

Thank you @brianvanburken

**Comment by brianvanburken** [comment]
It seems that the previous PR #8 broke the build

**Comment by webhive** [comment]
+1 --compressed flag work

**Comment by tapickell** [comment]
Just adding `--compressed` by hand to the install and list-all scripts till this gets merged.

**Comment by drewolson** [comment]
This works for me as well. Would love to see it merged.

**Pull request merged**
